### ISSUE TITLE
Issue when only 1 item in the slideshow

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-slideshow-changelog#1]
I encountered an issue when the slideshow only contains a single item. The slideshow dots and arrows are all enabled and when clicking on an arrow, the item will animate to a blank slate and then glitch back to the initial position.

My suggestion would be to only enable the arrows, dots, autoplay and animations if more than 1 item is present in the slideshow.

I managed to fix this manually on the website I'm working on, but would be great if this would be done automatically by the plugin.

**Comment by claudia-romano** [comment]
Hi there,
thanks for the heads-up. We just pushed a new version fixing this issue. Cheers!
