### ISSUE TITLE
laggy transition when there is no background

### ISSUE THREAD

**Issue by Samanw** [CodyHouse/cd-slideshow-changelog#10]
Hi,
there is a problem with slideshow which make it laggy when you set a **slide background transparent** and it shows previous selected slide when the transition is completed for 0.1sec

**Comment by claudia-romano** [comment]
Hi there,
I tried recreating the bug using our live demo, without success. Here's a video:
https://www.dropbox.com/scl/fi/s4lgrt2b641i8whxw72pa/codyhouse-slideshow.mp4?dl=0&rlkey=f0rlwjz4cusanjjr7u36b9m1p

Could you provide more info on recreating the bug? Thanks

**Comment by Samanw** [comment]
https://www.dropbox.com/s/iyagwt471bz3ji6/Rec%200001.mp4?dl=0
check the video please, notice that when i change the slide , the button of previous slide appears and then disappears

**Comment by claudia-romano** [comment]
Hi there, unfortunately we cannot check custom code. Could you provide the steps to reproduce the bug starting from the CodyHouse component? Also, which version are you using? Thanks.

**Comment by Samanw** [comment]
this is the code

[sldieshow.txt](https://github.com/codyhouse/cd-slideshow-changelog/files/12061227/sldieshow.txt)

from this component
https://codyhouse.co/ds/components/app/slideshow--transition-slide

**Comment by claudia-romano** [comment]
Thanks for providing this. We have pushed an updated version of the component fixing this issue. You can get the updated SCSS/CSS code here:
https://codyhouse.co/ds/components/app/slideshow

I'm closing this issue for now. But feel free to reopen it if you are still experiencing issues. Cheers!
