### ISSUE TITLE
--transition-fade bug in Firefox

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-slideshow-changelog#3]
Hi Codyhouse-Team,

there seems to be a bug with the --transition-fade effect in Firefox (76.0.1).
I use the slideshow in a project with these parameters:
data-swipe="on"
data-autoplay="on"

When the slides change sometimes the fade effect does not show. So between the slides is no effect visible, it is just a hard cut.
See in the video below. At minute 0:33 and 0:42 there is no effect when the slides change.
https://drive.google.com/file/d/1zTpfBBaenXD7i_JZvCoXs5pZTsjkm_EN/view?usp=sharing

In Chrome everything is working fine.

EDIT:
The fade-bug is also visible in Chrome:
Have a look at our Project: http://relaunch.lohse-diamantbohrtechnik.de/

Regards
Sven

**Comment by w3work** [comment]
Hey CodyHouse-Team,
could please give a response to this problem/bug?
We need a smooth transition between the slides for our project and it seems the current slideshow doesn`t provide this.

**Comment by claudia-romano** [comment]
Hi there, we have pushed an updated version of the component fixing the bug on Firefox. You can get the updated SCSS code from the component page:
https://codyhouse.co/ds/components/app/slideshow

Feel free to reopen this issue if you are still having problems. Cheers.

**Comment by w3work** [comment]
Hi Claudia,

thanks for the feedback and the updated version.
It is working now fine in Firefox!

Thank you very much.
