### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by jacmaes** [CodyHouse/cd-slideshow-changelog#4]
It would a great usability enhancement to be able to use the left and right arrows to go the previous and next slide, just like on the lightbox component. Thanks.

**Comment by claudia-romano** [comment]
Hi there, we just pushed an updated version of the Slideshow component. You can now use the keyboard to navigate when the slideshow element is in focus. 
You can get the updated code here:
https://codyhouse.co/ds/components/app/slideshow

Cheers!

**Comment by jacmaes** [comment]
Wonderful. Thanks!
