### ISSUE TITLE
Ho ti initialize the slideshow when DOM changes?

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-slideshow-changelog#5]
Hi i facing a little problem here. I have a page where i change the content of the slideshow without loading the page, but the images do not show because i need to initialize the slideshow.

So i'm struggling is there a way to initialize the slideshow when the DOM changes ?

**Comment by claudia-romano** [comment]
Hi there, the Slideshow component has the `Slideshow` public object you can use to initialise it:
```
var slideshowEl = document.getElementsByClassName('js-slideshow')[0];

new Slideshow({
  element: slideshowEl,
  navigation: true, // show dots navigation
  autoplay : false, 
  autoplayInterval : false, 
  swipe : false
});
```
We'll make sure to update the component Info page! Cheers.

**Comment by yankeyhotel** [comment]
Will this code "reinitialize" the slideshow?

I want the slideshow to load. Later some new slides will be added. Then I'd like to reinitialize the slideshow.

When I initialize the Slideshow object after new slides have been added, nothing really happens. Thank you. I'm using CodyFrame v3.

**Comment by yankeyhotel** [comment]
Ok, I figured out what was happening. I had to re-add all the `.slideshow__nav-item`... then reinitialize.

Hope this helps someone else. :)
