### ISSUE TITLE
Issue when only 1 item in the slideshow

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-slideshow-changelog#7]
When there is only one slide-show item, the navigation dots and the arrows still show. Is there a way to remove these when only one slide is present?

**Comment by claudia-romano** [comment]
Hi there, are you using the latest version of the component? This bug has already been fixed. More here https://github.com/CodyHouse/cd-slideshow-changelog/issues/1

Cheers!

**Comment by bacounts** [comment]
I actually found the issue. The .is-hidden class was not applying for some reason locally on my end. It seems to be working now. Thanks!
