### ISSUE TITLE
Chrome and Firefox error after minification of script.js

### ISSUE THREAD

**Issue by yankeyhotel** [CodyHouse/cd-slideshow-changelog#9]
https://agencyhabitat.com/case_study/7-eleven-franchising/

```
scripts.min.js?ver=1682376124:1 Uncaught TypeError: Util.extend is not a function
    at new d (scripts.min.js?ver=1682376124:1:429317)
    at new t (scripts.min.js?ver=1682376124:1:462385)
    at scripts.min.js?ver=1682376124:1:464043
    at scripts.min.js?ver=1682376124:1:464055
```

Recently we switched to using `scripts.min.js` but something seems to be happening when the file is minimized. The error does appear in Safari, but does in error in Chrome and Firefox. `Util.extend` is declared right before the slideshow function as copied from Codyhouse (https://codyhouse.co/ds/components/app/slideshow). Also, the error didn't show up on the non-minified version.

**Comment by claudia-romano** [comment]
Hi there,
did you try minifying only the JS of the slideshow component? The error you get could be related to some other code imported right before the slideshow. I tried minifying the component JS (I used uglify) and I was not able to recreate the issue. Also, what tool are you using? Thanks

**Comment by claudia-romano** [comment]
I'm closing this as no additional info was provided. Feel free to reopen it if you are still experiencing the bug. Cheers!
